version: '3'
services:
    mongo:
        image: mongo
        ports:
            - "27018:27017"
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        links:
            - mongo
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
    